services:
  - type: web
    name: climatesense-ai
    runtime: python
    buildCommand: ./setup.sh
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PERPLEXITY_API_KEY
        sync: false  # You'll set this manually in Render dashboard
